-- Auto Generated (Do not modify) 89EEF263C9CC16B5C4BF9C298467D3B33EF52DAE62A000D33B1113B919E15345
CREATE     VIEW [SCP_Core_Wrk].[v_DimFiscalCalendar] AS (SELECT [DateID] AS [Transaction Date]
      ,[DateKey] AS [Integer Date]
      ,[MapicsDate] AS [Mapics Date]
	  ,[CalendarDayOfWeekName] AS [Day of Week]
	  ,[FiscalWeek] AS [Fiscal Week Num]
	  ,CONCAT('FW ', RIGHT(CONCAT('00',[FiscalWeek]),2)) AS [FW Desc]
	  ,[FiscalWeekYear] AS [Fiscal Year Week Num]
	  ,[FiscalMonth] AS [Fiscal Month Num]
	  ,CONCAT('FM ', RIGHT(CONCAT('00',[FiscalMonth]),2)) AS [FM Desc]
	  ,FORMAT(CONVERT(DATE,CONCAT([FiscalMonthYear],'01')), 'MMM') AS [Fiscal Month Name]
	  ,[FiscalMonthYear] AS [Fiscal Year Month Num]
	  ,FORMAT(CONVERT(DATE,CONCAT([FiscalMonthYear],'01')), 'MMM yyyy') AS [Fiscal Month Year Desc]
	  ,CONVERT(DATE,CONCAT([FiscalMonthYear],'01')) AS [Fiscal Month (calendar start)]
	  ,[FiscalQuarter] AS [Fiscal Quarter Num]
	  ,CONCAT('FQ ', RIGHT(CONCAT('00',[FiscalQuarter]),2)) AS [FQ Desc]
	  ,[FiscalSemesterYear] AS [Fiscal Year Half Num]
	  ,[FiscalSemester] AS [Fiscal Half Num]  
	  ,CONCAT('FH ', RIGHT(CONCAT('00',[FiscalSemester]),2)) AS [FH Desc]
	  ,[FiscalYear] AS [Fiscal Year]
	  ,CONCAT('FY ', [FiscalYear]) AS [FY Desc]
	  ,CONVERT(DATE,[FiscalWeekFirstDate]) AS [Fiscal Week Start]
	  ,CONVERT(DATE, [FiscalWeekLastDate]) AS [Fiscal Week End]
	  ,CONVERT(DATE,[FiscalMonthFirstDate]) AS [Fiscal Month Start]
	  ,CONVERT(DATE,[FiscalMonthLastDate]) AS [Fiscal Month End]
	  ,CONVERT(DATE,[FiscalYearFirstDate]) AS [Fiscal Year Start]
	  ,CONVERT(DATE,[FiscalYearLastDate]) AS [Fiscal Year End]
	  ,[HolidayIndicator] AS [Holiday Indicator]
	  ,[HolidayName] AS [Holiday Name]
	  ,[WeekdayWeekend]
	  ,[CalendarWeek] AS [Calendar Week Num]
	  ,[CalendarMonth] AS [Calendar Month Num]
	  ,[CalendarQuarter] AS [Calendar Quarter Num]
	  ,[CalendarYear] AS [Calendar Year]
	  ,[FiscalDateIndicator] AS [Fiscal Day Indicator]
      ,[FiscalWeekIndicator] AS [Fiscal Week Indicator]
      ,[FiscalMonthIndicator] AS [Fiscal Month Indicator]
      ,[FiscalQuarterIndicator] AS [Fiscal Quarter Indicator]
      ,[FiscalYearIndicator] AS [Fiscal Year Indicator]
  FROM [Enterprise_Lakehouse].[MasterData_DW].[DimDate]
  WHERE [FiscalYearIndicator] BETWEEN -5 AND 5)