CREATE TABLE [SCP_Core].[DimFiscalCalendar] (

	[Transaction Date] date NOT NULL, 
	[Integer Date] int NOT NULL, 
	[Mapics Date] int NOT NULL, 
	[Day of Week] varchar(9) NOT NULL, 
	[Fiscal Week Num] int NOT NULL, 
	[FW Desc] char(5) NOT NULL, 
	[Fiscal Year Week Num] int NOT NULL, 
	[Fiscal Month Num] int NOT NULL, 
	[FM Desc] char(5) NOT NULL, 
	[Fiscal Month Name] char(3) NOT NULL, 
	[Fiscal Year Month Num] int NOT NULL, 
	[Fiscal Month Year Desc] char(8) NOT NULL, 
	[Fiscal Month (calendar start)] date NOT NULL, 
	[Fiscal Quarter Num] int NOT NULL, 
	[FQ Desc] char(5) NOT NULL, 
	[Fiscal Year Half Num] int NOT NULL, 
	[Fiscal Half Num] int NOT NULL, 
	[FH Desc] char(5) NOT NULL, 
	[Fiscal Year] int NOT NULL, 
	[FY Desc] char(7) NOT NULL, 
	[Fiscal Week Start] date NOT NULL, 
	[Fiscal Week End] date NOT NULL, 
	[Fiscal Month Start] date NOT NULL, 
	[Fiscal Month End] date NOT NULL, 
	[Fiscal Year Start] date NOT NULL, 
	[Fiscal Year End] date NOT NULL, 
	[Holiday Indicator] varchar(11) NOT NULL, 
	[Holiday Name] varchar(25) NULL, 
	[WeekdayWeekend] char(7) NOT NULL, 
	[Calendar Week Num] int NOT NULL, 
	[Calendar Month Num] int NOT NULL, 
	[Calendar Quarter Num] int NOT NULL, 
	[Calendar Year] int NOT NULL, 
	[Fiscal Day Indicator] int NOT NULL, 
	[Fiscal Week Indicator] int NOT NULL, 
	[Fiscal Month Indicator] int NOT NULL, 
	[Fiscal Quarter Indicator] int NOT NULL, 
	[Fiscal Year Indicator] int NOT NULL
);