CREATE TABLE [SCP_Core].[DimSCPItemMaster] (

	[Item SKU] varchar(8000) NOT NULL, 
	[Item Description] varchar(8000) NULL, 
	[Item SKU Description] varchar(8000) NOT NULL, 
	[Item Code] varchar(8000) NULL, 
	[Series Number] varchar(8000) NULL, 
	[Ext Series Number] varchar(8000) NULL, 
	[Planning Series] varchar(8000) NULL, 
	[Series Name] varchar(8000) NULL, 
	[Series Color] varchar(8000) NULL, 
	[Colors] varchar(8000) NULL, 
	[Frame Number] varchar(8000) NULL, 
	[Series Description] varchar(8000) NULL, 
	[Item Forecast Planner ID] varchar(8000) NULL, 
	[Item Forecast Planner ID (Dim)] varchar(8000) NULL, 
	[AFI Item Status] varchar(8000) NULL, 
	[Future Status] varchar(8000) NULL, 
	[Item Name] varchar(8000) NULL, 
	[Item Class] varchar(8000) NULL, 
	[Item Class Code] varchar(8000) NULL, 
	[Item Class Name] varchar(8000) NULL, 
	[Collective Class] varchar(8000) NULL, 
	[AFI Sales Division] varchar(8000) NULL, 
	[Item Grouping] varchar(8000) NULL, 
	[Association Code] varchar(8000) NULL, 
	[Showroom] varchar(8000) NULL, 
	[Product Line] varchar(8000) NULL, 
	[Hold Buy Code] varchar(8000) NULL, 
	[Item Image] varchar(8000) NULL, 
	[Image URL] varchar(8000) NULL, 
	[Quantity In Box] decimal(4,0) NULL, 
	[UOM] varchar(8000) NULL, 
	[Cubes] decimal(5,2) NULL, 
	[Seats] decimal(5,2) NULL, 
	[Product Height Meters] decimal(7,2) NULL, 
	[Product Width Meters] decimal(7,2) NULL, 
	[Product Depth Meters] decimal(7,2) NULL, 
	[Carton Height Meters] decimal(7,2) NULL, 
	[Carton Width Meters] decimal(7,2) NULL, 
	[Carton Depth Meters] decimal(7,2) NULL, 
	[Product Height Inches] decimal(7,2) NULL, 
	[Product Width Inches] decimal(7,2) NULL, 
	[Product Depth Inches] decimal(7,2) NULL, 
	[Carton Height Inches] decimal(7,2) NULL, 
	[Carton Width Inches] decimal(7,2) NULL, 
	[Carton Depth Inches] decimal(7,2) NULL, 
	[Item Description Series] varchar(8000) NULL, 
	[SH Item Description Series] varchar(8000) NULL, 
	[SH Series Description] varchar(8000) NULL, 
	[Item Description Series Item Color] varchar(8000) NULL, 
	[Child Style Description] varchar(8000) NULL, 
	[Parent Style Description] varchar(8000) NULL, 
	[Item Consumer Description] varchar(8000) NULL, 
	[Retail Type Description] varchar(8000) NULL, 
	[Main Piece Item] varchar(8000) NULL, 
	[Retail Category Code] varchar(8000) NULL, 
	[Retail Category Description] varchar(8000) NULL, 
	[Retail Category Name] varchar(8000) NULL, 
	[Retail Department Name] varchar(8000) NULL, 
	[Retail Category Group] varchar(8000) NULL, 
	[Retail Category Charge Type] varchar(8000) NULL, 
	[AFI Finance Division] varchar(8000) NULL, 
	[AFI Finance Division Code] varchar(8000) NULL, 
	[AFI Sales Category Code] varchar(8000) NULL, 
	[AFI Sales Category] varchar(8000) NULL, 
	[Item Style Code] varchar(8000) NULL, 
	[Item Style Group] varchar(8000) NULL, 
	[Item Style] varchar(8000) NULL, 
	[Division] varchar(8000) NULL, 
	[AFI Sales Division Code] varchar(8000) NULL, 
	[Key Item] bit NULL, 
	[Item Type] varchar(8000) NULL, 
	[Sellable Item Flag] varchar(8000) NULL, 
	[Manufacturing Status] varchar(8000) NULL, 
	[Responsible Office] varchar(8000) NULL, 
	[Responsible Office Name] varchar(8000) NULL, 
	[Import Domestic Code] varchar(8000) NULL, 
	[Country Of Origin] varchar(8000) NULL, 
	[Primary Vendor] varchar(8000) NULL, 
	[Manufacturing Status Change Date] date NULL, 
	[New Item Flag] bit NULL, 
	[Discontinued Flag] bit NULL, 
	[Discontinued Year Period] varchar(8000) NULL, 
	[Common Carrier Flag] varchar(8000) NULL, 
	[Express Ship Flag] varchar(8000) NULL, 
	[Discontinued Date] date NULL, 
	[Series Date Archived] date NULL, 
	[Series Discontinued Flag] bit NULL, 
	[Previous Status Code] varchar(8000) NULL, 
	[Status Code Change Date] date NULL, 
	[Current Unit Cost] decimal(19,8) NULL, 
	[CEX Code] varchar(8000) NULL, 
	[Market Introduced At] varchar(8000) NULL, 
	[Merchandising Category] smallint NULL, 
	[Price Point] int NULL, 
	[Series Grouping] smallint NULL, 
	[Master Group Code] varchar(8000) NULL, 
	[Marketing Item Status] varchar(8000) NULL, 
	[Marketing Status Description] varchar(8000) NULL, 
	[Lifestyle] varchar(8000) NULL, 
	[Commodity Item] bit NULL, 
	[F123 Product Flag] bit NULL, 
	[HS Core Product Flag] bit NULL, 
	[HS Proprietary Product Flag] bit NULL, 
	[HS Exclusive Flag] bit NULL, 
	[Berkline Product Flag] bit NULL, 
	[Benchcraft Product Flag] bit NULL, 
	[New Millennium Product Flag] bit NULL, 
	[Bardini Product Flag] bit NULL, 
	[Shanghai Store] bit NULL, 
	[Default Group] bit NULL, 
	[Good Better Best For Price Point] varchar(8000) NULL, 
	[GBB Sort Id] int NULL, 
	[Initial Invoice Period] varchar(8000) NULL, 
	[Initial Invoice Qty] decimal(38,0) NULL, 
	[Market Begin Date] date NULL, 
	[Market End Date] date NULL, 
	[FOB Arc Price] decimal(8,2) NULL, 
	[Division Ranking] int NULL, 
	[Trend Arrow] varchar(8000) NULL, 
	[Item Merch Grid Override Photo] varchar(8000) NULL, 
	[Group Price Incr] decimal(5,0) NULL, 
	[Group Price Point Type] varchar(8000) NULL, 
	[Exclusive Comment] varchar(8000) NULL, 
	[Series Image] varchar(8000) NULL, 
	[Sofa Table Series Flag] varchar(8000) NULL, 
	[Recliner Series Flag] varchar(8000) NULL, 
	[Power Motion Series Flag] varchar(8000) NULL, 
	[Wedge Series Flag] varchar(8000) NULL, 
	[Dining Series Flag] varchar(8000) NULL, 
	[Item Third Party Item] varchar(8000) NULL, 
	[Series Third Party] varchar(8000) NULL, 
	[Item Home Store Product Line] varchar(8000) NULL, 
	[Item Ecom Merchant Notes] varchar(8000) NULL, 
	[Item Amazon Brand Owner] varchar(8000) NULL, 
	[Item Supplier Direct Ship Only] varchar(8000) NULL, 
	[Consumer Choice Flag] varchar(8000) NULL, 
	[Eligible For Protection Plan] varchar(8000) NULL, 
	[Is Protection Plan] varchar(8000) NULL, 
	[Friendly Dimensions] varchar(8000) NULL, 
	[Knockout] varchar(8000) NULL, 
	[Scene7 Image Set] varchar(8000) NULL, 
	[Fluff AFI] varchar(8000) NULL, 
	[Series Primary] varchar(8000) NULL, 
	[Series Main Image] varchar(8000) NULL, 
	[Stand Alone Flag] varchar(8000) NULL, 
	[Supp Weight Net Weight Lbs] varchar(8000) NULL, 
	[Unit Weight Lbs] varchar(8000) NULL, 
	[UPC] varchar(8000) NULL, 
	[Retail Brand Name] varchar(8000) NULL, 
	[Mfg Warranty] varchar(8000) NULL, 
	[Material] varchar(8000) NULL, 
	[Series Features] varchar(8000) NULL, 
	[Item Is RTA] varchar(8000) NULL, 
	[Primary Channel Sku] varchar(8000) NULL, 
	[Primary Series Name] varchar(8000) NULL, 
	[Primary Series Number] varchar(8000) NULL, 
	[E Retail Channel Sku] varchar(8000) NULL, 
	[E Retail Series Name] varchar(8000) NULL, 
	[E Retail Series Number] varchar(8000) NULL, 
	[Item Table Shape Type] varchar(8000) NULL, 
	[Item Bed Size Type] varchar(8000) NULL, 
	[Item Bed Style Type] varchar(8000) NULL, 
	[Item General Color] varchar(8000) NULL, 
	[Item Price Point Rating] varchar(8000) NULL, 
	[Part Flag] varchar(4) NOT NULL, 
	[Kit Flag] varchar(2) NOT NULL
);