CREATE TABLE [bronze].[brz_wholesale_codis_afi__codatan] (

	[id_order] varchar(8000) NULL, 
	[id_item_sku] varchar(8000) NULL, 
	[code_warehouse] varchar(8000) NULL, 
	[num_item_sequence] int NULL, 
	[qty_ordered] decimal(12,3) NULL, 
	[qty_shipped] decimal(12,3) NULL, 
	[qty_backordered] decimal(12,3) NULL, 
	[amt_extended_selling] decimal(12,2) NULL, 
	[amt_list_price] decimal(12,4) NULL, 
	[amt_selling_price] decimal(12,4) NULL, 
	[amt_unit_cost] decimal(14,8) NULL, 
	[amt_negotiated_price] decimal(12,4) NULL, 
	[amt_unit_purchase_order] decimal(12,4) NULL, 
	[amt_price_adjustment] decimal(12,2) NULL, 
	[amt_selling_price_current] decimal(14,7) NULL, 
	[amt_list_price_original] decimal(12,4) NULL, 
	[amt_extended_selling_original] decimal(12,2) NULL, 
	[amt_price_history] decimal(12,4) NULL, 
	[amt_list_price_history] decimal(12,4) NULL, 
	[amt_extended_selling_history] decimal(12,2) NULL, 
	[amt_selling_price_history] decimal(14,7) NULL, 
	[val_weight] decimal(12,3) NULL, 
	[val_extended_weight] decimal(12,3) NULL, 
	[val_extended_weight_original] decimal(12,3) NULL, 
	[dt_requested] date NULL, 
	[dt_manufactured] date NULL, 
	[dt_last_schedule_change] datetime2(6) NULL, 
	[dt_previous_load] datetime2(6) NULL, 
	[dt_prior_load_change] datetime2(6) NULL, 
	[dt_earliest_load] datetime2(6) NULL, 
	[dt_latest_load] datetime2(6) NULL, 
	[id_customer] varchar(8000) NULL, 
	[code_ship_to] varchar(8000) NULL, 
	[name_mark_for] varchar(8000) NULL, 
	[name_item_description] varchar(8000) NULL, 
	[name_item_description_short] varchar(8000) NULL, 
	[code_item_class] varchar(8000) NULL, 
	[code_item_type] varchar(8000) NULL, 
	[code_unit_measure] varchar(8000) NULL, 
	[code_record] varchar(8000) NULL, 
	[code_wholesale] varchar(8000) NULL, 
	[code_carrier] varchar(8000) NULL, 
	[code_pattern] varchar(200) NULL, 
	[code_last_unit_measure] varchar(8000) NULL, 
	[code_tax_indicator] varchar(8000) NULL, 
	[code_correlation] varchar(8000) NULL, 
	[code_merge_order] varchar(8000) NULL, 
	[code_expedite_ad] varchar(8000) NULL, 
	[code_arrival_mode] varchar(8000) NULL, 
	[code_item_price_status] varchar(8000) NULL, 
	[num_load_date_changes] int NULL, 
	[num_last_promo] int NULL, 
	[num_price_multiple] int NULL, 
	[num_qty_per_dept] int NULL, 
	[code_allocation_flag] varchar(200) NULL, 
	[is_no_invoice] int NOT NULL, 
	[is_update_mc] int NOT NULL, 
	[is_update_mp] int NOT NULL, 
	[is_order_flag] int NOT NULL, 
	[is_round_override] int NOT NULL, 
	[is_method_override] int NOT NULL, 
	[is_negotiated_history] int NOT NULL, 
	[is_merge_order_flag] int NOT NULL, 
	[is_sale_flag] int NOT NULL, 
	[code_merge_date] varchar(200) NULL, 
	[_load_dt] datetime2(6) NULL
);