CREATE TABLE [bronze].[ref_customer_account] (

	[id_customer] varchar(8000) NULL, 
	[name_customer] varchar(8000) NULL, 
	[name_dba] varchar(8000) NULL, 
	[name_contact] varchar(8000) NULL, 
	[code_phone] varchar(8000) NULL, 
	[code_fax] varchar(8000) NULL, 
	[code_email] varchar(8000) NULL, 
	[code_territory] varchar(8000) NULL, 
	[id_credit_territory] varchar(200) NULL, 
	[id_deduct_territory] varchar(200) NULL, 
	[code_customer_channel] varchar(8000) NULL, 
	[code_customer_class] varchar(8000) NULL, 
	[amt_credit_limit] decimal(14,2) NULL, 
	[code_terms] varchar(8000) NULL, 
	[num_terms_days] int NULL, 
	[pct_available_credit] decimal(10,2) NULL, 
	[code_credit_authorization] varchar(8000) NULL, 
	[code_minimum_freight] varchar(8000) NULL, 
	[amt_min_preapproval] decimal(14,2) NULL, 
	[code_credit_address] varchar(8000) NULL, 
	[pct_late_charge] decimal(10,4) NULL, 
	[is_cancel_backorders] int NOT NULL, 
	[is_allow_partial_shipment] int NOT NULL, 
	[is_allow_allowance_credits] int NOT NULL, 
	[is_documentation_hold] int NOT NULL, 
	[is_pars_by_purchaser] int NOT NULL, 
	[is_10_digit_schedule_b] int NOT NULL, 
	[is_inherit_blocking] int NOT NULL, 
	[code_language] varchar(8000) NULL, 
	[code_statement] int NULL, 
	[code_item_cross_reference] varchar(8000) NULL, 
	[code_currency] varchar(8000) NULL, 
	[code_tax_id] varchar(8000) NULL, 
	[code_app] int NULL, 
	[code_homestore_facing_warehouse] varchar(8000) NULL, 
	[code_insurance_type] varchar(8000) NULL, 
	[dt_insurance_expiration] datetime2(6) NULL, 
	[amt_insurance_coverage_requested] decimal(14,2) NULL, 
	[amt_insurance_coverage_approved] decimal(14,2) NULL, 
	[code_insurance_status] varchar(8000) NULL, 
	[code_record_status] varchar(8000) NULL, 
	[id_billing_address] int NULL, 
	[name_memo] varchar(8000) NULL, 
	[num_change_customer_ar] int NULL, 
	[num_change_customer] int NULL, 
	[num_change_customer_ext] int NULL, 
	[num_commission_audit] int NULL, 
	[dt_territory_change] datetime2(6) NULL, 
	[dt_last_status_change] datetime2(6) NULL, 
	[name_created_by] varchar(8000) NULL, 
	[ts_created] datetime2(6) NULL, 
	[name_modified_by] varchar(8000) NULL, 
	[ts_modified] datetime2(6) NULL, 
	[_load_dt] datetime2(6) NULL
);