[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "VendorMaster_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "VendorNumber", DestinationColumnName = "VendorNumber"], [SourceColumnName = "VendorName", DestinationColumnName = "VendorName"], [SourceColumnName = "Office", DestinationColumnName = "Office"], [SourceColumnName = "VendorOfficeLocation", DestinationColumnName = "VendorOfficeLocation"], [SourceColumnName = "VendorDesc", DestinationColumnName = "VendorDesc"], [SourceColumnName = "Country", DestinationColumnName = "Country"], [SourceColumnName = "LeadTime", DestinationColumnName = "LeadTime"], [SourceColumnName = "AFILeadTime", DestinationColumnName = "AFILeadTime"], [SourceColumnName = "WVFLeadTime", DestinationColumnName = "WVFLeadTime"], [SourceColumnName = "VendorActive", DestinationColumnName = "VendorActive"], [SourceColumnName = "Vendor Import Domestic Flag", DestinationColumnName = "Vendor Import Domestic Flag"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared VendorMaster = // Vendor Master

let
  Source = Sql.Database("ashley-edw.database.windows.net", "ashley_edw", [CommandTimeout = #duration(0, 1, 0, 0), CreateNavigationProperties = false]),
  #"Navigation 1" = Source{[Schema = "PowerBI_SupplyChain", Item = "VendorMaster"]}[Data],
  #"Filtered rows" = Table.SelectRows(#"Navigation 1", each [Country] <> "" and [VendorName] <> null and [VendorName] <> ""),
  #"Changed column type" = Table.TransformColumnTypes(#"Filtered rows", {{"LeadTime", Int64.Type}, {"AFILeadTime", Int64.Type}, {"WVFLeadTime", Int64.Type}})
in
  #"Changed column type";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "WarehouseMaster_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "Warehouse", DestinationColumnName = "Warehouse"], [SourceColumnName = "Warehouse Location", DestinationColumnName = "Warehouse Location"], [SourceColumnName = "Site ID", DestinationColumnName = "Site ID"], [SourceColumnName = "Warehouse Name", DestinationColumnName = "Warehouse Name"], [SourceColumnName = "Warehouse Order Group", DestinationColumnName = "Warehouse Order Group"], [SourceColumnName = "Intransit Warehouse", DestinationColumnName = "Intransit Warehouse"], [SourceColumnName = "Container Direct Warehouse", DestinationColumnName = "Container Direct Warehouse"], [SourceColumnName = "Controlled Warehouse", DestinationColumnName = "Controlled Warehouse"], [SourceColumnName = "AFIWarehousesKey", DestinationColumnName = "AFIWarehousesKey"], [SourceColumnName = "Warehouse Group", DestinationColumnName = "Warehouse Group"], [SourceColumnName = "Sort By", DestinationColumnName = "Sort By"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared WarehouseMaster = // Warehouse Master

let
  Source = Sql.Database("ashley-edw.database.windows.net", "ashley_edw", [CommandTimeout = #duration(0, 1, 0, 0), CreateNavigationProperties = false]),
  #"Navigation 1" = Source{[Schema = "PowerBI_SupplyChain", Item = "WarehouseMaster"]}[Data],
  #"Inserted conditional column" = Table.AddColumn(#"Navigation 1", "Warehouse Group", each if [Warehouse Code] = "335" then "Ashton" else if [Warehouse Code] = "C35" then "Ashton" else if [Warehouse Code] = "232" then "Wanvog" else if [Warehouse Code] = "C" then "C/CNW" else if [Warehouse Code] = "CNW" then "C/CNW" else if [Warehouse Code] = "C99" then "C/CNW" else if [Warehouse Code] = "AF" then "C/CNW" else if [Warehouse Code] = "IOR" then "C/CNW" else if [Warehouse Code] = "101" then "PROD" else if [Warehouse Code] = "12 " then "PROD" else if [Warehouse Code] = "151" then "PROD" else if [Warehouse Code] = "20 " then "PROD" else if [Warehouse Code] = "201" then "PROD" else if [Warehouse Code] = "3  " then "PROD" else if [Warehouse Code] = "60 " then "PROD" else if [Warehouse Code] = "15A" then "RH" else if [Warehouse Code] = "17A" then "RH" else if [Warehouse Code] = "19A" then "RH" else if [Warehouse Code] = "1A " then "RH" else if [Warehouse Code] = "28A" then "RH" else if [Warehouse Code] = "42A" then "RH" else if [Warehouse Code] = "5A " then "RH" else if [Warehouse Code] = "ECA" then "RH" else if [Warehouse Code] = "55 " then "VENDOR DIRECT" else if [Warehouse Code] = "213" then "3PLs" else if [Warehouse Code] = "215" then "3PLs" else if [Warehouse Code] = "242" then "3PLs" else if [Warehouse Code] = "49 " then "3PLs" else if [Warehouse Code] = "50 " then "3PLs" else if [Warehouse Code] = "52 " then "3PLs" else if [Warehouse Code] = "10 " then "DO NOT USE" else if [Warehouse Code] = "109" then "DO NOT USE" else if [Warehouse Code] = "14 " then "DO NOT USE" else if [Warehouse Code] = "18 " then "DO NOT USE" else if [Warehouse Code] = "2  " then "DO NOT USE" else if [Warehouse Code] = "21 " then "N/A" else if [Warehouse Code] = "232" then "DO NOT USE" else if [Warehouse Code] = "6  " then "DO NOT USE" else if [Warehouse Code] = "7  " then "N/A" else if [Warehouse Code] = "8  " then "DO NOT USE" else if [Warehouse Code] = "9  " then "N/A" else if [Warehouse Code] = "P  " then "N/A" else if [Warehouse Code] = "R  " then "N/A" else if [Warehouse Code] = "W  " then "N/A" else "AFI" ),
  #"Changed column type" = Table.TransformColumnTypes(#"Inserted conditional column", {{"Warehouse Group", type text}}),
  #"Inserted conditional column2" = Table.AddColumn(#"Changed column type", "Sort By", 
  each if [Warehouse Code] = "1  " then "1" else if [Warehouse Code] = "15 " then "2" else if [Warehouse Code] = "16 " then "3" else if [Warehouse Code] = "17 " then "4" else if [Warehouse Code] = "19 " then "5" 
  else if [Warehouse Code] = "28 " then "6" else if [Warehouse Code] = "42 " then "7" else if [Warehouse Code] = "5  " then "8" else if [Warehouse Code] = "70 " then "9" else if [Warehouse Code] = "ECR" then "10" 
  else if [Warehouse Code] = "335" then "11" else if [Warehouse Code] = "C35" then "12" else if [Warehouse Code] = "C  " then "13" else if [Warehouse Code] = "C99" then "14" else if [Warehouse Code] = "CNW" then "15" else if [Warehouse Code] = "AF " then "16" else if [Warehouse Code] = "IOR" then "17"
  else if [Warehouse Code] = "12 " then "18" else if [Warehouse Code] = "101" then "19" else if [Warehouse Code] = "151" then "20" else if [Warehouse Code] = "20 " then "21" else if [Warehouse Code] = "201" then "22" 
  else if [Warehouse Code] = "3  " then "23" else if [Warehouse Code] = "60 " then "24" else if [Warehouse Code] = "1A " then "25" else if [Warehouse Code] = "15A" then "26" else if [Warehouse Code] = "17A" then "27" 
  else if [Warehouse Code] = "19A" then "28" else if [Warehouse Code] = "28A" then "29" else if [Warehouse Code] = "42A" then "30" else if [Warehouse Code] = "5A " then "31" else if [Warehouse Code] = "ECA" then "32" 
  else if [Warehouse Code] = "55 " then "33" else if [Warehouse Code] = "213" then "34" else if [Warehouse Code] = "215" then "35" else if [Warehouse Code] = "242" then "36" else if [Warehouse Code] = "49 " then "37" 
  else if [Warehouse Code] = "50 " then "38" else if [Warehouse Code] = "52 " then "39" else if [Warehouse Code] = "10 " then "40" else if [Warehouse Code] = "109" then "41" else if [Warehouse Code] = "14 " then "42" 
  else if [Warehouse Code] = "18 " then "43" else if [Warehouse Code] = "2  " then "44" else if [Warehouse Code] = "21 " then "53" else if [Warehouse Code] = "232" then "64" else if [Warehouse Code] = "6  " then "47" 
  else if [Warehouse Code] = "7  " then "48" else if [Warehouse Code] = "8  " then "49" else if [Warehouse Code] = "9  " then "50" else if [Warehouse Code] = "P  " then "51" else if [Warehouse Code] = "R  " then "52" 
  else if [Warehouse Code] = "W  " then "53"  else "" ),
  #"Changed column type2" = Table.TransformColumnTypes(#"Inserted conditional column2", {{"Sort By", type text}}),
  #"Renamed columns" = Table.RenameColumns(#"Changed column type2", {{"Warehouse Code", "Warehouse"}}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Renamed columns", {{"Sort By", Int64.Type}}),
  #"Trimmed text" = Table.TransformColumns(#"Changed column type 1", {{"Warehouse", each Text.Trim(_), type text}})
in
  #"Trimmed text";
shared VendorMaster_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "c8d9fc83-18b6-4e1d-8264-0b49eed36fe0"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "3ca38f6c-666b-4f50-ab1b-bb72cf1778ea"]}[Data],
  TableNavigation = Navigation_2{[Item = "VendorMaster", Schema = "dbo"]}?[Data]?
in
  TableNavigation;
shared WarehouseMaster_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "c8d9fc83-18b6-4e1d-8264-0b49eed36fe0"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "3ca38f6c-666b-4f50-ab1b-bb72cf1778ea"]}[Data],
  TableNavigation = Navigation_2{[Item = "WarehouseMaster", Schema = "dbo"]}?[Data]?
in
  TableNavigation;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "FiscalCal_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "Transaction Date", DestinationColumnName = "Transaction Date"], [SourceColumnName = "Integer Date", DestinationColumnName = "Integer Date"], [SourceColumnName = "Mapics Date", DestinationColumnName = "Mapics Date"], [SourceColumnName = "Day of Week", DestinationColumnName = "Day of Week"], [SourceColumnName = "Fiscal Week Num", DestinationColumnName = "Fiscal Week Num"], [SourceColumnName = "FW Desc", DestinationColumnName = "FW Desc"], [SourceColumnName = "Fiscal Year Week Num", DestinationColumnName = "Fiscal Year Week Num"], [SourceColumnName = "Fiscal Month Num", DestinationColumnName = "Fiscal Month Num"], [SourceColumnName = "FM Desc", DestinationColumnName = "FM Desc"], [SourceColumnName = "Fiscal Month Name", DestinationColumnName = "Fiscal Month Name"], [SourceColumnName = "Fiscal Year Month Num", DestinationColumnName = "Fiscal Year Month Num"], [SourceColumnName = "Fiscal Month Year Desc", DestinationColumnName = "Fiscal Month Year Desc"], [SourceColumnName = "Fiscal Month Calendar Start", DestinationColumnName = "Fiscal Month Calendar Start"], [SourceColumnName = "Fiscal Quarter Num", DestinationColumnName = "Fiscal Quarter Num"], [SourceColumnName = "FQ Desc", DestinationColumnName = "FQ Desc"], [SourceColumnName = "Fiscal Year Half Num", DestinationColumnName = "Fiscal Year Half Num"], [SourceColumnName = "Fiscal Half Num", DestinationColumnName = "Fiscal Half Num"], [SourceColumnName = "FH Desc", DestinationColumnName = "FH Desc"], [SourceColumnName = "Fiscal Year", DestinationColumnName = "Fiscal Year"], [SourceColumnName = "FY Desc", DestinationColumnName = "FY Desc"], [SourceColumnName = "Fiscal Week Start", DestinationColumnName = "Fiscal Week Start"], [SourceColumnName = "Fiscal Week End", DestinationColumnName = "Fiscal Week End"], [SourceColumnName = "Fiscal Month Start", DestinationColumnName = "Fiscal Month Start"], [SourceColumnName = "Fiscal Month End", DestinationColumnName = "Fiscal Month End"], [SourceColumnName = "Fiscal Year Start", DestinationColumnName = "Fiscal Year Start"], [SourceColumnName = "Fiscal Year End", DestinationColumnName = "Fiscal Year End"], [SourceColumnName = "Holiday Indicator", DestinationColumnName = "Holiday Indicator"], [SourceColumnName = "Holiday Name", DestinationColumnName = "Holiday Name"], [SourceColumnName = "WeekdayWeekend", DestinationColumnName = "WeekdayWeekend"], [SourceColumnName = "Calendar Week Num", DestinationColumnName = "Calendar Week Num"], [SourceColumnName = "Calendar Month Num", DestinationColumnName = "Calendar Month Num"], [SourceColumnName = "Calendar Quarter Num", DestinationColumnName = "Calendar Quarter Num"], [SourceColumnName = "Calendar Year", DestinationColumnName = "Calendar Year"], [SourceColumnName = "Fiscal Day Indicator", DestinationColumnName = "Fiscal Day Indicator"], [SourceColumnName = "Fiscal Week Indicator", DestinationColumnName = "Fiscal Week Indicator"], [SourceColumnName = "Fiscal Month Indicator", DestinationColumnName = "Fiscal Month Indicator"], [SourceColumnName = "Fiscal Quarter Indicator", DestinationColumnName = "Fiscal Quarter Indicator"], [SourceColumnName = "Fiscal Year Indicator", DestinationColumnName = "Fiscal Year Indicator"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared FiscalCal = // Ashley Fiscal Calendar 
let
  Source = Sql.Database("ashley-edw.database.windows.net", "ashley_edw", [CommandTimeout = #duration(0, 1, 0, 0), Query = "/***** PowerBI_SupplyChain.AshleyFiscalCalendar ******/#(lf)#(lf)SELECT [DateID] AS [Transaction Date]#(lf)      ,[DateKey] AS [Integer Date]#(lf)      ,[MapicsDate] AS [Mapics Date]#(lf)#(tab)  ,[CalendarDayOfWeekName] AS [Day of Week]#(lf)#(tab)  ,[FiscalWeek] AS [Fiscal Week Num]#(lf)#(tab)  ,CONCAT('FW ', RIGHT(CONCAT('00',[FiscalWeek]),2)) AS [FW Desc]#(lf)#(tab)  ,[FiscalWeekYear] AS [Fiscal Year Week Num]#(lf)#(tab)  ,[FiscalMonth] AS [Fiscal Month Num]#(lf)#(tab)  ,CONCAT('FM ', RIGHT(CONCAT('00',[FiscalMonth]),2)) AS [FM Desc]#(lf)#(tab)  ,FORMAT(CONVERT(DATE,CONCAT([FiscalMonthYear],'01')), 'MMM') AS [Fiscal Month Name]#(lf)#(tab)  ,[FiscalMonthYear] AS [Fiscal Year Month Num]#(lf)#(tab)  ,FORMAT(CONVERT(DATE,CONCAT([FiscalMonthYear],'01')), 'MMM yyyy') AS [Fiscal Month Year Desc]#(lf)#(tab)  ,CONVERT(DATE,CONCAT([FiscalMonthYear],'01')) AS [Fiscal Month Calendar Start]#(lf)#(tab)  ,[FiscalQuarter] AS [Fiscal Quarter Num]#(lf)#(tab)  ,CONCAT('FQ ', RIGHT(CONCAT('00',[FiscalQuarter]),2)) AS [FQ Desc]#(lf)#(tab)  ,[FiscalSemesterYear] AS [Fiscal Year Half Num]#(lf)#(tab)  ,[FiscalSemester] AS [Fiscal Half Num]  #(lf)#(tab)  ,CONCAT('FH ', RIGHT(CONCAT('00',[FiscalSemester]),2)) AS [FH Desc]#(lf)#(tab)  ,[FiscalYear] AS [Fiscal Year]#(lf)#(tab)  ,CONCAT('FY ', [FiscalYear]) AS [FY Desc]#(lf)#(tab)  ,CONVERT(DATE,[FiscalWeekFirstDate]) AS [Fiscal Week Start]#(lf)#(tab)  ,CONVERT(DATE, [FiscalWeekLastDate]) AS [Fiscal Week End]#(lf)#(tab)  ,CONVERT(DATE,[FiscalMonthFirstDate]) AS [Fiscal Month Start]#(lf)#(tab)  ,CONVERT(DATE,[FiscalMonthLastDate]) AS [Fiscal Month End]#(lf)#(tab)  ,CONVERT(DATE,[FiscalYearFirstDate]) AS [Fiscal Year Start]#(lf)#(tab)  ,CONVERT(DATE,[FiscalYearLastDate]) AS [Fiscal Year End]#(lf)#(tab)  ,[HolidayIndicator] AS [Holiday Indicator]#(lf)#(tab)  ,[HolidayName] AS [Holiday Name]#(lf)#(tab)  ,[WeekdayWeekend]#(lf)#(tab)  ,[CalendarWeek] AS [Calendar Week Num]#(lf)#(tab)  ,[CalendarMonth] AS [Calendar Month Num]#(lf)#(tab)  ,[CalendarQuarter] AS [Calendar Quarter Num]#(lf)#(tab)  ,[CalendarYear] AS [Calendar Year]#(lf)#(tab)  ,[FiscalDateIndicator] AS [Fiscal Day Indicator]#(lf)      ,[FiscalWeekIndicator] AS [Fiscal Week Indicator]#(lf)      ,[FiscalMonthIndicator] AS [Fiscal Month Indicator]#(lf)      ,[FiscalQuarterIndicator] AS [Fiscal Quarter Indicator]#(lf)      ,[FiscalYearIndicator] AS [Fiscal Year Indicator]#(lf)  FROM [Enterprise_DW].[DimDate]#(lf)  WHERE [FiscalYearIndicator] BETWEEN -4 AND 4#(lf)", CreateNavigationProperties = false]),
  #"Changed column type" = Table.TransformColumnTypes(Source, {{"Transaction Date", type date}, {"Fiscal Month Calendar Start", type date}, {"Fiscal Week Start", type date}, {"Fiscal Week End", type date}, {"Fiscal Month Start", type date}, {"Fiscal Month End", type date}, {"Fiscal Year Start", type date}, {"Fiscal Year End", type date}, {"Fiscal Month Num", Int64.Type}, {"Fiscal Quarter Num", Int64.Type}, {"Fiscal Half Num", Int64.Type}, {"Calendar Week Num", Int64.Type}, {"Calendar Month Num", Int64.Type}, {"Calendar Quarter Num", Int64.Type}, {"Fiscal Week Num", Int64.Type}})
in
  #"Changed column type";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "CustomerMaster_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "Account And ShipTo Number", DestinationColumnName = "Account And ShipTo Number"], [SourceColumnName = "Account Number", DestinationColumnName = "Account Number"], [SourceColumnName = "ShipTo Number", DestinationColumnName = "ShipTo Number"], [SourceColumnName = "Customer Name", DestinationColumnName = "Customer Name"], [SourceColumnName = "Account Name", DestinationColumnName = "Account Name"], [SourceColumnName = "ShipTo Details", DestinationColumnName = "ShipTo Details"], [SourceColumnName = "Customer Segment", DestinationColumnName = "Customer Segment"], [SourceColumnName = "Business Type Code", DestinationColumnName = "Business Type Code"], [SourceColumnName = "Business Type", DestinationColumnName = "Business Type"], [SourceColumnName = "Reporting Business Type", DestinationColumnName = "Reporting Business Type"], [SourceColumnName = "Customer Group", DestinationColumnName = "Customer Group"], [SourceColumnName = "Address 1", DestinationColumnName = "Address 1"], [SourceColumnName = "Address 2", DestinationColumnName = "Address 2"], [SourceColumnName = "Address 3", DestinationColumnName = "Address 3"], [SourceColumnName = "Address 4", DestinationColumnName = "Address 4"], [SourceColumnName = "Address 5", DestinationColumnName = "Address 5"], [SourceColumnName = "City", DestinationColumnName = "City"], [SourceColumnName = "State", DestinationColumnName = "State"], [SourceColumnName = "ZipCode", DestinationColumnName = "ZipCode"], [SourceColumnName = "Country", DestinationColumnName = "Country"], [SourceColumnName = "State Code", DestinationColumnName = "State Code"], [SourceColumnName = "Country Code", DestinationColumnName = "Country Code"], [SourceColumnName = "Latitude", DestinationColumnName = "Latitude"], [SourceColumnName = "Longitude", DestinationColumnName = "Longitude"], [SourceColumnName = "Account Exception Flag", DestinationColumnName = "Account Exception Flag"], [SourceColumnName = "Customer Shipto Name", DestinationColumnName = "Customer Shipto Name"], [SourceColumnName = "Shipto AddressID", DestinationColumnName = "Shipto AddressID"], [SourceColumnName = "Primary Sales Territory", DestinationColumnName = "Primary Sales Territory"], [SourceColumnName = "Shipto Sales Territory", DestinationColumnName = "Shipto Sales Territory"], [SourceColumnName = "Customer Account Status", DestinationColumnName = "Customer Account Status"], [SourceColumnName = "Default Warehouse", DestinationColumnName = "Default Warehouse"], [SourceColumnName = "Route Zone", DestinationColumnName = "Route Zone"], [SourceColumnName = "Route Region", DestinationColumnName = "Route Region"], [SourceColumnName = "ABC Account-Current Year", DestinationColumnName = "ABC Account-Current Year"], [SourceColumnName = "ABC Account-Previous Year", DestinationColumnName = "ABC Account-Previous Year"], [SourceColumnName = "ABC Account-2 Years Ago", DestinationColumnName = "ABC Account-2 Years Ago"], [SourceColumnName = "Commission Code", DestinationColumnName = "Commission Code"], [SourceColumnName = "Account Group", DestinationColumnName = "Account Group"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared CustomerMaster = // Customer Master 
let
  Source = Sql.Database("ashley-edw.database.windows.net", "ashley_edw", [CommandTimeout = #duration(0, 1, 0, 0), Query = "#(lf)SELECT *#(tab)#(tab)#(tab)#(tab)#(lf)FROM [PowerBI_SupplyChain].[CustomerAcctMaster_AFI]#(lf)                      ", CreateNavigationProperties = false]),
  #"Changed column type" = Table.TransformColumnTypes(Source, {{"Customer Segment", type text}}),
  #"Trimmed text" = Table.TransformColumns(#"Changed column type", {{"Account And ShipTo Number", each Text.Trim(_), type nullable text}})
in
  #"Trimmed text";
shared CustomerMaster_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "c8d9fc83-18b6-4e1d-8264-0b49eed36fe0"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "3ca38f6c-666b-4f50-ab1b-bb72cf1778ea"]}[Data],
  TableNavigation = Navigation_2{[Item = "CustomerMaster", Schema = "dbo"]}?[Data]?
in
  TableNavigation;
shared FiscalCal_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "c8d9fc83-18b6-4e1d-8264-0b49eed36fe0"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "3ca38f6c-666b-4f50-ab1b-bb72cf1778ea"]}[Data],
  TableNavigation = Navigation_2{[Item = "FiscalCal", Schema = "dbo"]}?[Data]?
in
  TableNavigation;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "ItemMaster_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "Item SKU", DestinationColumnName = "Item SKU"], [SourceColumnName = "Item Description", DestinationColumnName = "Item Description"], [SourceColumnName = "ItemSKU Description", DestinationColumnName = "ItemSKU Description"], [SourceColumnName = "Colors", DestinationColumnName = "Colors"], [SourceColumnName = "Series Number", DestinationColumnName = "Series Number"], [SourceColumnName = "Series Name", DestinationColumnName = "Series Name"], [SourceColumnName = "Series Description", DestinationColumnName = "Series Description"], [SourceColumnName = "Ext Series Number", DestinationColumnName = "Ext Series Number"], [SourceColumnName = "Ext Series Description", DestinationColumnName = "Ext Series Description"], [SourceColumnName = "Item Ext Series Number", DestinationColumnName = "Item Ext Series Number"], [SourceColumnName = "Series Color", DestinationColumnName = "Series Color"], [SourceColumnName = "Item Grouping", DestinationColumnName = "Item Grouping"], [SourceColumnName = "Item Class Code", DestinationColumnName = "Item Class Code"], [SourceColumnName = "Item Class Name", DestinationColumnName = "Item Class Name"], [SourceColumnName = "Collective Class Code", DestinationColumnName = "Collective Class Code"], [SourceColumnName = "Collective Class", DestinationColumnName = "Collective Class"], [SourceColumnName = "Responsible Office", DestinationColumnName = "Responsible Office"], [SourceColumnName = "Product Line", DestinationColumnName = "Product Line"], [SourceColumnName = "AFI Finance Division", DestinationColumnName = "AFI Finance Division"], [SourceColumnName = "AFI Sales Division Code", DestinationColumnName = "AFI Sales Division Code"], [SourceColumnName = "AFI Sales Division", DestinationColumnName = "AFI Sales Division"], [SourceColumnName = "AFI Sales Category Code", DestinationColumnName = "AFI Sales Category Code"], [SourceColumnName = "AFI Sales Category", DestinationColumnName = "AFI Sales Category"], [SourceColumnName = "Retail Category Code", DestinationColumnName = "Retail Category Code"], [SourceColumnName = "Retail Category Description", DestinationColumnName = "Retail Category Description"], [SourceColumnName = "FOB Price", DestinationColumnName = "FOB Price"], [SourceColumnName = "Import/Domestic Code", DestinationColumnName = "Import/Domestic Code"], [SourceColumnName = "Qty In Box", DestinationColumnName = "Qty In Box"], [SourceColumnName = "UOM", DestinationColumnName = "UOM"], [SourceColumnName = "Main Piece Item", DestinationColumnName = "Main Piece Item"], [SourceColumnName = "Main Piece", DestinationColumnName = "Main Piece"], [SourceColumnName = "Primary Vendor", DestinationColumnName = "Primary Vendor"], [SourceColumnName = "Primary Vendor Name", DestinationColumnName = "Primary Vendor Name"], [SourceColumnName = "Item Style Code", DestinationColumnName = "Item Style Code"], [SourceColumnName = "Item Style Group", DestinationColumnName = "Item Style Group"], [SourceColumnName = "AFI Item Status", DestinationColumnName = "AFI Item Status"], [SourceColumnName = "Manufacturing Status", DestinationColumnName = "Manufacturing Status"], [SourceColumnName = "Manufacturing Status Change Date", DestinationColumnName = "Manufacturing Status Change Date"], [SourceColumnName = "ItemForecastPlannerID", DestinationColumnName = "ItemForecastPlannerID"], [SourceColumnName = "Cubes", DestinationColumnName = "Cubes"], [SourceColumnName = "ContainerVolume", DestinationColumnName = "ContainerVolume"], [SourceColumnName = "Unit Price", DestinationColumnName = "Unit Price"], [SourceColumnName = "Current Status", DestinationColumnName = "Current Status"], [SourceColumnName = "Future Status", DestinationColumnName = "Future Status"], [SourceColumnName = "Current SCP Manufacturing Status", DestinationColumnName = "Current SCP Manufacturing Status"], [SourceColumnName = "ItemImage", DestinationColumnName = "ItemImage"], [SourceColumnName = "Image URL", DestinationColumnName = "Image URL"], [SourceColumnName = "Sales Class Code", DestinationColumnName = "Sales Class Code"], [SourceColumnName = "Sales Class Description", DestinationColumnName = "Sales Class Description"], [SourceColumnName = "Marketing Item Status", DestinationColumnName = "Marketing Item Status"], [SourceColumnName = "Marketing Status Description", DestinationColumnName = "Marketing Status Description"], [SourceColumnName = "Discount Class Code", DestinationColumnName = "Discount Class Code"], [SourceColumnName = "Discount Class Description", DestinationColumnName = "Discount Class Description"], [SourceColumnName = "Commission Class Code", DestinationColumnName = "Commission Class Code"], [SourceColumnName = "Commission Class Description", DestinationColumnName = "Commission Class Description"], [SourceColumnName = "Freight Class Code", DestinationColumnName = "Freight Class Code"], [SourceColumnName = "Freight Class Description", DestinationColumnName = "Freight Class Description"], [SourceColumnName = "Country of Origin", DestinationColumnName = "Country of Origin"], [SourceColumnName = "CEX Code", DestinationColumnName = "CEX Code"], [SourceColumnName = "Commodity Item", DestinationColumnName = "Commodity Item"], [SourceColumnName = "Market Introduced At", DestinationColumnName = "Market Introduced At"], [SourceColumnName = "Market Begin Date", DestinationColumnName = "Market Begin Date"], [SourceColumnName = "Market End Date", DestinationColumnName = "Market End Date"], [SourceColumnName = "Initial Invoice Period", DestinationColumnName = "Initial Invoice Period"], [SourceColumnName = "Initial Invoice Qty", DestinationColumnName = "Initial Invoice Qty"], [SourceColumnName = "Merchandising Category", DestinationColumnName = "Merchandising Category"], [SourceColumnName = "Child Style Description", DestinationColumnName = "Child Style Description"], [SourceColumnName = "Parent Style Description", DestinationColumnName = "Parent Style Description"], [SourceColumnName = "Price Point", DestinationColumnName = "Price Point"], [SourceColumnName = "Item Code", DestinationColumnName = "Item Code"], [SourceColumnName = "Association Code", DestinationColumnName = "Association Code"], [SourceColumnName = "Default Group", DestinationColumnName = "Default Group"], [SourceColumnName = "Sellable Item Flag", DestinationColumnName = "Sellable Item Flag"], [SourceColumnName = "ExpressShipFlag", DestinationColumnName = "ExpressShipFlag"], [SourceColumnName = "ConsumerChoiceFlag", DestinationColumnName = "ConsumerChoiceFlag"], [SourceColumnName = "F123 Product Flag", DestinationColumnName = "F123 Product Flag"], [SourceColumnName = "HS Core Product Flag", DestinationColumnName = "HS Core Product Flag"], [SourceColumnName = "HS Proprietary Product Flag", DestinationColumnName = "HS Proprietary Product Flag"], [SourceColumnName = "HS Exclusive Flag", DestinationColumnName = "HS Exclusive Flag"], [SourceColumnName = "Berkline Product Flag", DestinationColumnName = "Berkline Product Flag"], [SourceColumnName = "Benchcraft Product Flag", DestinationColumnName = "Benchcraft Product Flag"], [SourceColumnName = "New Millennium Product Flag", DestinationColumnName = "New Millennium Product Flag"], [SourceColumnName = "Bardini Product Flag", DestinationColumnName = "Bardini Product Flag"], [SourceColumnName = "Shanghai Store", DestinationColumnName = "Shanghai Store"], [SourceColumnName = "Price Point Rating", DestinationColumnName = "Price Point Rating"], [SourceColumnName = "General Description Code", DestinationColumnName = "General Description Code"], [SourceColumnName = "General Description", DestinationColumnName = "General Description"], [SourceColumnName = "Hold Buy Code", DestinationColumnName = "Hold Buy Code"], [SourceColumnName = "Showroom", DestinationColumnName = "Showroom"], [SourceColumnName = "HSExclusiveFlag", DestinationColumnName = "HSExclusiveFlag"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared ItemMaster = // Current Product Details
let
  Source = Sql.Database("ashley-edw.database.windows.net", "ashley_edw", [CommandTimeout = #duration(0, 1, 0, 0), CreateNavigationProperties = false]),
  #"Navigation 1" = Source{[Schema = "PowerBI_SupplyChain", Item = "CurrentProductDetails"]}[Data],
  #"Filtered rows" = Table.SelectRows(#"Navigation 1", each [Series Number] <> "#TRUD" and [Series Number] <> ".620 " and [Series Number] <> "00000" and [Series Number] <> "00001"),
  #"Sorted rows" = Table.Sort(#"Filtered rows", {{"Item SKU", Order.Ascending}}),
  #"Trimmed text" = Table.TransformColumns(#"Sorted rows", {{"Item SKU", each Text.Trim(_), type text}}),
  #"Duplicated column" = Table.DuplicateColumn(#"Trimmed text", "HS Exclusive Flag", "HSExclusiveFlag"),
  #"Removed duplicates" = Table.Distinct(#"Duplicated column", {"Item SKU"})
in
  #"Removed duplicates";
shared ItemMaster_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "c8d9fc83-18b6-4e1d-8264-0b49eed36fe0"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "3ca38f6c-666b-4f50-ab1b-bb72cf1778ea"]}[Data],
  TableNavigation = Navigation_2{[Item = "ItemMaster", Schema = "dbo"]}?[Data]?
in
  TableNavigation;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "SupplyPlanDetailToday_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "Item SKU", DestinationColumnName = "Item SKU"], [SourceColumnName = "Warehouse", DestinationColumnName = "Warehouse"], [SourceColumnName = "Week Ending", DestinationColumnName = "Week Ending"], [SourceColumnName = "Beginning Balance", DestinationColumnName = "Beginning Balance"], [SourceColumnName = "Prod - Firm", DestinationColumnName = "Prod - Firm"], [SourceColumnName = "Prod - Plan", DestinationColumnName = "Prod - Plan"], [SourceColumnName = "PO - Firm", DestinationColumnName = "PO - Firm"], [SourceColumnName = "PO - Plan", DestinationColumnName = "PO - Plan"], [SourceColumnName = "TI - In Trans", DestinationColumnName = "TI - In Trans"], [SourceColumnName = "TI - Firm", DestinationColumnName = "TI - Firm"], [SourceColumnName = "TI - Plan", DestinationColumnName = "TI - Plan"], [SourceColumnName = "Firm Demands", DestinationColumnName = "Firm Demands"], [SourceColumnName = "Promo Lift", DestinationColumnName = "Promo Lift"], [SourceColumnName = "Net Forecast", DestinationColumnName = "Net Forecast"], [SourceColumnName = "TO - Firm", DestinationColumnName = "TO - Firm"], [SourceColumnName = "TO - Plan", DestinationColumnName = "TO - Plan"], [SourceColumnName = "Total Receipts", DestinationColumnName = "Total Receipts"], [SourceColumnName = "Total Est Shipments", DestinationColumnName = "Total Est Shipments"], [SourceColumnName = "Total Prod", DestinationColumnName = "Total Prod"], [SourceColumnName = "Total PO", DestinationColumnName = "Total PO"], [SourceColumnName = "Total TI", DestinationColumnName = "Total TI"], [SourceColumnName = "Total Demand", DestinationColumnName = "Total Demand"], [SourceColumnName = "Total TO", DestinationColumnName = "Total TO"], [SourceColumnName = "SI", DestinationColumnName = "SI"], [SourceColumnName = "SS", DestinationColumnName = "SS"], [SourceColumnName = "SI -SS", DestinationColumnName = "SI -SS"], [SourceColumnName = "SI Neg", DestinationColumnName = "SI Neg"], [SourceColumnName = "Demand Fulfillment", DestinationColumnName = "Demand Fulfillment"], [SourceColumnName = "Snapshot Date", DestinationColumnName = "Snapshot Date"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared SupplyPlanDetailToday = let
    Source = Sql.Database("ashley-edw.database.windows.net", "ashley_edw"),
    SupplyPlanDetail = Source{[Schema="Wholesale_DemandPlanning_AFI",Item="SupplyPlanDetail"]}[Data],
    
    // Filter data
    FilteredData = Table.SelectRows(SupplyPlanDetail, each 
        Date.From([dtea]) = Date.From(List.Max(SupplyPlanDetail[dtea])) and 
        not List.Contains({"213", "215", "242"}, [spdWarehouse])),
    
    // Transform columns
    TransformedData = Table.TransformColumns(FilteredData, {
        {"spdItem", Text.Trim, type text},
        {"spdWarehouse", Text.Trim, type text},
        {"spdWeekEnding", Date.From, type date},
        {"dtea", Date.From, type date}
    }),
    
    // Add calculated columns one by one
    AddTotalEstShipments = Table.AddColumn(TransformedData, "Total Est Shipments", each try [spdDemandFulfillment] + [spdFirmTransferOut] + [spdPlannedTransferOut] otherwise null, type number),
    AddTotalProd = Table.AddColumn(AddTotalEstShipments, "Total Prod", each try [spdFirmProduction] + [spdPlannedProduction] otherwise null, type number),
    AddTotalPO = Table.AddColumn(AddTotalProd, "Total PO", each try [spdFirmPurchaseOrders] + [spdPlannedPurchaseOrders] otherwise null, type number),
    AddTotalTI = Table.AddColumn(AddTotalPO, "Total TI", each try [spdInTransitTransferIn] + [spdOnOrderTransferIn] + [spdPlannedTransferIn] otherwise null, type number),
    AddTotalDemand = Table.AddColumn(AddTotalTI, "Total Demand", each try [spdFirmDemands] + [spdNetForecast] otherwise null, type number),
    AddTotalTO = Table.AddColumn(AddTotalDemand, "Total TO", each try [spdFirmTransferOut] + [spdPlannedTransferOut] otherwise null, type number),
    AddSISS = Table.AddColumn(AddTotalTO, "SI -SS", each try [spdShippableInventory] - [spdSafetyStock] otherwise null, type number),
    AddSINeg = Table.AddColumn(AddSISS, "SI Neg", each if [spdShippableInventory] < 0 then [spdShippableInventory] else 0, type number),
    
    // Select final columns
    SelectColumns = Table.SelectColumns(AddSINeg, {
        "spdItem", "spdWarehouse", "spdWeekEnding", "spdBeginingBalance", 
        "spdFirmProduction", "spdPlannedProduction", "spdFirmPurchaseOrders",
        "spdPlannedPurchaseOrders", "spdInTransitTransferIn", "spdOnOrderTransferIn",
        "spdPlannedTransferIn", "spdFirmDemands", "spdWeeklyPromotionalLift",
        "spdNetForecast", "spdFirmTransferOut", "spdPlannedTransferOut",
        "spdTotalReceipts", "Total Est Shipments", "Total Prod", "Total PO",
        "Total TI", "Total Demand", "Total TO", "spdShippableInventory",
        "spdSafetyStock", "SI -SS", "SI Neg", "spdDemandFulfillment", "dtea"
    }),
    
    // Rename columns
    RenamedColumns = Table.RenameColumns(SelectColumns, {
        {"spdItem", "Item SKU"},
        {"spdWarehouse", "Warehouse"},
        {"spdWeekEnding", "Week Ending"},
        {"spdBeginingBalance", "Beginning Balance"},
        {"spdFirmProduction", "Prod - Firm"},
        {"spdPlannedProduction", "Prod - Plan"},
        {"spdFirmPurchaseOrders", "PO - Firm"},
        {"spdPlannedPurchaseOrders", "PO - Plan"},
        {"spdInTransitTransferIn", "TI - In Trans"},
        {"spdOnOrderTransferIn", "TI - Firm"},
        {"spdPlannedTransferIn", "TI - Plan"},
        {"spdFirmDemands", "Firm Demands"},
        {"spdWeeklyPromotionalLift", "Promo Lift"},
        {"spdNetForecast", "Net Forecast"},
        {"spdFirmTransferOut", "TO - Firm"},
        {"spdPlannedTransferOut", "TO - Plan"},
        {"spdTotalReceipts", "Total Receipts"},
        {"spdShippableInventory", "SI"},
        {"spdSafetyStock", "SS"},
        {"spdDemandFulfillment", "Demand Fulfillment"},
        {"dtea", "Snapshot Date"}
    }),
  #"Changed column type" = Table.TransformColumnTypes(RenamedColumns, {{"Beginning Balance", Int64.Type}, {"Prod - Firm", Int64.Type}, {"Prod - Plan", Int64.Type}, {"PO - Firm", Int64.Type}, {"PO - Plan", Int64.Type}, {"TI - In Trans", Int64.Type}, {"TI - Firm", Int64.Type}, {"TI - Plan", Int64.Type}, {"Firm Demands", Int64.Type}, {"Promo Lift", Int64.Type}, {"Net Forecast", Int64.Type}, {"TO - Firm", Int64.Type}, {"TO - Plan", Int64.Type}, {"Total Receipts", Int64.Type}, {"Total Est Shipments", Int64.Type}, {"Total Prod", Int64.Type}, {"Total PO", Int64.Type}, {"Total TI", Int64.Type}, {"Total Demand", Int64.Type}, {"Total TO", Int64.Type}, {"SI", Int64.Type}, {"SS", Int64.Type}, {"SI -SS", Int64.Type}, {"SI Neg", Int64.Type}, {"Demand Fulfillment", Int64.Type}}),
  #"Trimmed text" = Table.TransformColumns(#"Changed column type", {{"Item SKU", each Text.Trim(_), type text}, {"Warehouse", each Text.Trim(_), type text}})
in
    #"Trimmed text";
shared SupplyPlanDetailToday_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false]),
  Navigation_1 = Pattern{[workspaceId = "c8d9fc83-18b6-4e1d-8264-0b49eed36fe0"]}[Data],
  Navigation_2 = Navigation_1{[warehouseId = "3ca38f6c-666b-4f50-ab1b-bb72cf1778ea"]}[Data],
  TableNavigation = Navigation_2{[Item = "SupplyPlanDetailToday", Schema = "dbo"]}?[Data]?
in
  TableNavigation;
