-- Auto Generated (Do not modify) A5BD5C3A9BC40C574BD1618958010C8E55C5DE4A5FAA740F8DB4F8C498D32C42

CREATE   VIEW bronze.vw_brz_wholesale_codis_afi__codatan AS
SELECT
    TRIM(ORDNO)                                         AS id_order,
    TRIM(ITNBR)                                         AS id_item_sku,
    TRIM(HOUSE)                                         AS code_warehouse,
    CAST(ITMSQ AS INT)                                  AS num_item_sequence,
    CAST(COQTY AS DECIMAL(12,3))                        AS qty_ordered,
    CAST(QTYSH AS DECIMAL(12,3))                        AS qty_shipped,
    CAST(QTYBO AS DECIMAL(12,3))                        AS qty_backordered,
    CAST(INSAM AS DECIMAL(12,2))                        AS amt_extended_selling,
    CAST(ISLPR AS DECIMAL(12,4))                        AS amt_list_price,
    CAST(PRICE AS DECIMAL(12,4))                        AS amt_selling_price,
    CAST(UNITC AS DECIMAL(14,8))                        AS amt_unit_cost,
    CAST(NEGPR AS DECIMAL(12,4))                        AS amt_negotiated_price,
    CAST(UNTPO AS DECIMAL(12,4))                        AS amt_unit_purchase_order,
    CAST(PRADJ AS DECIMAL(12,2))                        AS amt_price_adjustment,
    CAST(ISCPR AS DECIMAL(14,7))                        AS amt_selling_price_current,
    CAST(ISLPO AS DECIMAL(12,4))                        AS amt_list_price_original,
    CAST(INSAO AS DECIMAL(12,2))                        AS amt_extended_selling_original,
    CAST(PRICH AS DECIMAL(12,4))                        AS amt_price_history,
    CAST(ISLPH AS DECIMAL(12,4))                        AS amt_list_price_history,
    CAST(INSAH AS DECIMAL(12,2))                        AS amt_extended_selling_history,
    CAST(ISCPH AS DECIMAL(14,7))                        AS amt_selling_price_history,
    CAST(WEGHT AS DECIMAL(12,3))                        AS val_weight,
    CAST(EXTWT AS DECIMAL(12,3))                        AS val_extended_weight,
    CAST(EXTWO AS DECIMAL(12,3))                        AS val_extended_weight_original,
    TRY_CONVERT(DATE, CAST(RQIDT AS VARCHAR(20)))       AS dt_requested,
    TRY_CONVERT(DATE, CAST(MFIDT AS VARCHAR(20)))       AS dt_manufactured,
    TRY_CAST(LSLDDTCH AS DATETIME2(6))                  AS dt_last_schedule_change,
    TRY_CAST(PRVLDDTE AS DATETIME2(6))                   AS dt_previous_load,
    TRY_CAST(PRLDDTCH AS DATETIME2(6))                  AS dt_prior_load_change,
    TRY_CAST(EARLDDT AS DATETIME2(6))                    AS dt_earliest_load,
    TRY_CAST(LATLDDT AS DATETIME2(6))                    AS dt_latest_load,
    TRIM(CCUSNO)                                        AS id_customer,
    TRIM(CSHPNO)                                        AS code_ship_to,
    TRIM(MARKFOR)                                       AS name_mark_for,
    TRIM(ITDSC)                                         AS name_item_description,
    TRIM(ITDSI)                                         AS name_item_description_short,
    TRIM(ITCLS)                                         AS code_item_class,
    TRIM(ITTYP)                                         AS code_item_type,
    TRIM(UNMSR)                                         AS code_unit_measure,
    TRIM(RCDCD)                                         AS code_record,
    TRIM(WHSLC)                                         AS code_wholesale,
    TRIM(CRCOD)                                         AS code_carrier,
    CAST(PTRCD AS VARCHAR(200))                         AS code_pattern,
    TRIM(LSTUM)                                         AS code_last_unit_measure,
    TRIM(TXIND)                                         AS code_tax_indicator,
    TRIM(COREL)                                         AS code_correlation,
    TRIM(MORDN)                                         AS code_merge_order,
    TRIM(EXPAD)                                         AS code_expedite_ad,
    TRIM(ARRVLMODE)                                     AS code_arrival_mode,
    TRIM(ITMPRCSTS)                                     AS code_item_price_status,
    CAST(NUMLDDTCHG AS INT)                             AS num_load_date_changes,
    CAST(LPMNO AS INT)                                  AS num_last_promo,
    CAST(PMULT AS INT)                                  AS num_price_multiple,
    CAST(QPDPT AS INT)                                  AS num_qty_per_dept,
    CAST(IAFLG AS VARCHAR(200))                         AS code_allocation_flag,
    CASE WHEN CAST(NOINV AS INT) != 0 THEN 1 ELSE 0 END  AS is_no_invoice,
    CASE WHEN CAST(UPDMC AS INT) != 0 THEN 1 ELSE 0 END  AS is_update_mc,
    CASE WHEN CAST(UPDMP AS DECIMAL(10,3)) != 0 THEN 1 ELSE 0 END AS is_update_mp,
    CASE WHEN CAST(ORFLG AS INT) != 0 THEN 1 ELSE 0 END  AS is_order_flag,
    CASE WHEN CAST(RDOVR AS INT) != 0 THEN 1 ELSE 0 END  AS is_round_override,
    CASE WHEN CAST(MDOVR AS INT) != 0 THEN 1 ELSE 0 END  AS is_method_override,
    CASE WHEN CAST(NEGRH AS DECIMAL(10,3)) != 0 THEN 1 ELSE 0 END AS is_negotiated_history,
    CASE WHEN CAST(MOFLG AS VARCHAR(10)) = '1' THEN 1 ELSE 0 END  AS is_merge_order_flag,
    CASE WHEN CAST(SAFLG AS VARCHAR(10)) = '1' THEN 1 ELSE 0 END  AS is_sale_flag,
    CAST(MRDTE AS VARCHAR(200))                         AS code_merge_date
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.codatan
WHERE ORDNO IS NOT NULL