-- Auto Generated (Do not modify) 7B8A754405E02F1DEBC9BA8B843B301CDD97C359C85E12763171769A87379BCF

CREATE   VIEW bronze.vw_brz_wholesale_codis_afi__extorit AS
SELECT
    TRIM(IORD)                                          AS id_order,
    CAST(ISEQ AS INT)                                   AS num_item_sequence,
    TRIM(IITEM)                                         AS id_item_sku,
    CAST(IEXCID AS INT)                                 AS id_exception,
    CAST(IGRPID AS INT)                                 AS id_group,
    CAST(IGRPNO AS INT)                                 AS num_group,
    CAST(ISLSN1 AS INT)                                 AS id_salesperson_1,
    CAST(ISLSN2 AS INT)                                 AS id_salesperson_2,
    CAST(IPRICE AS DECIMAL(14,4))                       AS amt_fob_price,
    CAST(IDSCNT AS DECIMAL(12,2))                       AS amt_discount,
    CAST(IDFIDC AS DECIMAL(12,2))                       AS amt_discount_fid,
    CAST(IFRGHT AS DECIMAL(12,2))                       AS amt_freight,
    CAST(IHDFRT AS DECIMAL(12,2))                       AS amt_handling_freight,
    CAST(ITDSCT AS DECIMAL(14,4))                       AS pct_total_discount,
    CAST(IFOBPR AS DECIMAL(12,2))                       AS amt_fob_price_base,
    CAST(IREDUS AS VARCHAR(200))                        AS code_reduce,
    CAST(ICMADJ AS DECIMAL(12,2))                       AS amt_commission_adjustment,
    CAST(IPALLW AS DECIMAL(14,4))                       AS amt_price_allowance,
    CAST(ICONPR AS DECIMAL(12,2))                       AS amt_contract_price,
    CAST(ICOOPA AS DECIMAL(12,2))                       AS amt_coop_allowance,
    CAST(IATPQY AS DECIMAL(12,3))                       AS qty_atp,
    CAST(IATPQS AS DECIMAL(12,3))                       AS qty_atp_shipped,
    CAST(IATPWH AS DECIMAL(12,3))                       AS qty_atp_warehouse,
    TRIM(IDSCCD)                                        AS code_discount,
    TRIM(IDSCSC)                                        AS code_discount_schedule,
    TRIM(ICOMCD)                                        AS code_commission,
    TRIM(IPRCCD)                                        AS code_price,
    TRIM(IFRTCD)                                        AS code_freight_type,
    TRIM(IGBCOD)                                        AS code_global,
    TRIM(IORDST)                                        AS code_order_status,
    CAST(IRTECD AS VARCHAR(200))                        AS code_route,
    TRIM(IFSLSC)                                        AS code_first_sales_class,
    TRIM(ICSLSC)                                        AS code_current_sales_class,
    TRIM(IARVLMD)                                       AS code_arrival_mode,
    TRIM(IPRCSTS)                                       AS code_price_status,
    CAST(ICUS AS VARCHAR(200))                          AS id_customer,
    TRIM(ISTATE)                                        AS code_state,
    CAST(IWHSOP AS VARCHAR(200))                        AS code_warehouse_operation,
    CAST(ITRIP AS INT)                                  AS num_trip,
    CAST(IDROP AS INT)                                  AS num_drop,
    CAST(ICNTL AS INT)                                  AS num_control,
    CAST(IPRI AS INT)                                   AS num_priority,
    TRIM(ISTAT)                                         AS code_status,
    CAST(IREF AS VARCHAR(200))                          AS code_reference,
    CAST(IORDPRTY AS INT)                               AS num_order_priority,
    CAST(IPRGCNT AS INT)                                AS num_progress_count,
    CAST(ISCHCNT AS INT)                                AS num_schedule_count,
    CAST(ICNLCNT AS INT)                                AS num_cancel_count,
    CAST(IFRZCNT AS INT)                                AS num_freeze_count,
    CAST(ICDKCNT AS INT)                                AS num_cross_dock_count,
    TRIM(ILNRL)                                         AS code_line_rule,
    TRIM(IERRCM)                                        AS code_error_comment,
    CAST(ISLCM1 AS DECIMAL(14,4))                       AS val_sales_comment_1,
    CAST(ISLCM2 AS DECIMAL(14,4))                       AS val_sales_comment_2,
    TRY_CONVERT(DATE, CAST(IPRMDT AS VARCHAR(20)))      AS dt_promise,
    TRY_CONVERT(DATE, CAST(IOISDT AS VARCHAR(20)))      AS dt_original_issue,
    TRY_CONVERT(DATE, CAST(IMRDDT AS VARCHAR(20)))      AS dt_merge,
    TRY_CONVERT(DATE, CAST(IREDRT AS VARCHAR(20)))      AS dt_reduce,
    TRY_CONVERT(DATE, CAST(IARDTE AS VARCHAR(20)))      AS dt_arrival,
    CAST(IORINV AS INT)                                 AS num_original_invoice,
    TRY_CONVERT(DATE, CAST(IORGDLV AS VARCHAR(20)))     AS dt_delivery_original,
    TRY_CONVERT(DATE, CAST(ICNFDLV AS VARCHAR(20)))     AS dt_delivery_confirmed,
    TRY_CONVERT(DATE, CAST(IFRZDLV AS VARCHAR(20)))     AS dt_delivery_frozen,
    TRY_CONVERT(DATE, CAST(IFINDLV AS VARCHAR(20)))     AS dt_delivery_final,
    CAST(IPRTY AS INT)                                  AS num_delivery_priority,
    TRIM(IPKGID)                                        AS id_package,
    CAST(IPKGDA AS DECIMAL(12,3))                       AS val_package_data,
    CAST(IPKGPRC AS DECIMAL(12,2))                      AS amt_package_price,
    TRIM(IITMSTS)                                       AS code_item_status,
    CAST([IPKITM$] AS DECIMAL(12,2))                    AS amt_package_item,
    CAST(IPKITMDS AS DECIMAL(12,3))                     AS val_package_item_discount,
    TRIM(IACHORITM)                                     AS code_anchor_item,
    TRIM(IPKGDES)                                       AS name_package_description,
    CAST(IPDISD AS VARCHAR(200))                        AS code_price_discount,
    CAST(IPRCDT AS VARCHAR(200))                        AS code_price_date,
    CAST(IOCOMR AS VARCHAR(200))                        AS code_original_commission,
    TRIM(IJOBID)                                        AS id_job
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.EXTORIT
WHERE IORD IS NOT NULL