-- Auto Generated (Do not modify) 78A503658648204F4615EB0BDDEADC0EB72D32FCAFB37F9C0976613C91F1947F

CREATE   VIEW bronze.vw_brz_wholesale_codis_afi__extord AS
SELECT
    TRIM(XORDNO)                                        AS id_order,
    TRIM(CUSTNO)                                        AS id_customer,
    TRIM([SHPTO#])                                      AS code_ship_to,
    CAST(CSRPID AS INT)                                 AS id_csr,
    TRIM(ORDARR)                                        AS code_order_arrangement,
    TRIM(ORTYPE)                                        AS code_order_type,
    TRIM(ORDUSE)                                        AS code_order_use,
    TRIM(ORDREF)                                        AS code_order_reference,
    CAST(ORDLNK AS INT)                                 AS num_order_link,
    CAST(NOSETS AS INT)                                  AS num_sets,
    TRIM(ORDUSR)                                        AS name_order_user,
    TRIM(OTTYP1)                                        AS code_order_type_1,
    TRIM(OTTYP2)                                        AS code_order_type_2,
    TRIM(OTTYP3)                                        AS code_order_type_3,
    TRIM(OTTYP4)                                        AS code_order_type_4,
    TRY_CONVERT(DATE, CAST(RQSDAT AS VARCHAR(20)))      AS dt_requested_ship,
    TRY_CONVERT(DATE, CAST(TKNDAT AS VARCHAR(20)))      AS dt_taken,
    TRY_CONVERT(DATE, CAST(FRZDAT AS VARCHAR(20)))      AS dt_freeze,
    TRY_CONVERT(DATE, CAST(HDATE AS VARCHAR(20)))       AS dt_hold,
    TRY_CONVERT(DATE, CAST(CAPRDT AS VARCHAR(20)))      AS dt_capacity,
    TRY_CONVERT(DATE, CAST(CBDDAT AS VARCHAR(20)))      AS dt_cbd,
    TRY_CONVERT(DATE, CAST(DATMNT AS VARCHAR(20)))      AS dt_maintenance,
    CAST(TIMMNT AS VARCHAR(200))                        AS code_time_maintenance,
    TRIM(WHSE)                                          AS code_warehouse,
    TRIM(SHPNAM)                                        AS name_ship_to,
    TRIM(ZIPCOD)                                        AS code_zip,
    TRIM(EXTCTY)                                        AS code_city,
    TRIM(EXTSTE)                                        AS code_state,
    TRIM(TERRCD)                                        AS code_territory,
    TRIM(ARZONE)                                        AS code_ar_zone,
    CAST(ARSEQ AS INT)                                  AS num_ar_sequence,
    TRY_CONVERT(DATE, CAST(ARDATE AS VARCHAR(20)))      AS dt_ar,
    CAST([TRPNO] AS INT)                                AS num_trip,
    CAST([DROP#] AS INT)                                AS num_drop,
    CAST([TRIP#] AS INT)                                AS num_trip_sequence,
    TRIM(ADVTSP)                                        AS code_advance_transport,
    TRIM(CONTAC)                                        AS name_contact,
    TRIM([PHONE#])                                      AS code_phone,
    TRIM(CREDVW)                                        AS code_credit_review,
    TRIM(APVCHK)                                        AS code_approval_check,
    TRIM(APPROV)                                        AS name_approver,
    TRY_CAST(RCVCSH AS INT)                             AS num_received_cash,
    TRIM(CROVRD)                                        AS code_credit_override,
    TRY_CONVERT(DATE, CAST(CROVDT AS VARCHAR(20)))      AS dt_credit_override,
    TRIM(CRANOV)                                        AS code_credit_analysis_override,
    TRIM(COMMCO)                                        AS code_commission,
    TRIM(DSCNCO)                                        AS code_discount,
    TRIM(PRICCO)                                        AS code_price,
    TRIM(FRGHCO)                                        AS code_freight,
    TRIM(PRMNBR)                                        AS code_promo,
    CAST(MNTCNT AS INT)                                 AS num_maintenance_count,
    TRIM(USRMNT)                                        AS name_maintenance_user,
    TRIM(HLDUSR)                                        AS name_hold_user,
    CAST(REFNUM AS VARCHAR(200))                        AS code_reference_number
FROM Enterprise_Lakehouse.Wholesale_Codis_AFI.EXTORD
WHERE XORDNO IS NOT NULL