-- Auto Generated (Do not modify) 4A66B4E77DE343EBC6804346F1E0617B208D2A59BE8425B88A1564AA17790F71

CREATE   VIEW bronze.vw_ref_customer_shipping_location AS
SELECT
    TRIM(cslCustomerNumber)                                          AS id_customer,
    TRIM(cslShiptoNumber)                                            AS code_ship_to,
    CAST(cslMapicsSequenceNumber AS INT)                             AS num_mapics_sequence,
    TRIM(cslName)                                                    AS name_ship_to,
    TRIM(csmShpa1)                                                   AS name_address_1,
    TRIM(csmShpa2)                                                   AS name_address_2,
    TRIM(csmShpa3)                                                   AS name_address_3,
    TRIM(csmShpzp)                                                   AS code_zip,
    TRIM(csmShpst)                                                   AS code_state,
    TRIM(csmShpco)                                                   AS code_country,
    TRIM(csmCounty)                                                  AS code_county,
    TRIM(csmPhone)                                                   AS code_phone,
    TRIM(csmFaxTn)                                                   AS code_fax,
    TRIM(csmContact)                                                 AS name_contact,
    TRIM(csmWebsite)                                                 AS code_website,
    TRIM(csmEmail)                                                   AS code_email,
    TRIM(csmCsPhone)                                                 AS code_cs_phone,
    TRIM(csmcsFax)                                                   AS code_cs_fax,
    TRIM(csmcsContact)                                               AS name_cs_contact,
    TRIM(csmcsEmail)                                                 AS code_cs_email,
    TRIM(cslCommissionCode)                                          AS code_commission,
    TRIM(cslFreightCode)                                             AS code_freight,
    TRIM(cslPriceCode)                                               AS code_price,
    TRIM(cslDiscountCode)                                            AS code_discount,
    CAST(cslCommissionSplit AS DECIMAL(10,4))                        AS pct_commission_split,
    TRIM(cslDefaultWarehouse)                                        AS code_default_warehouse,
    TRIM(cslShippingTerritory)                                       AS code_shipping_territory,
    TRIM(cslBusinessType)                                            AS code_business_type,
    TRIM(cslShipType)                                                AS code_ship_type,
    TRIM(cslTranscomPrimaryID)                                       AS id_transcom_primary,
    TRIM(cslTranscomAlternateID)                                     AS id_transcom_alternate,
    TRIM(cslComment1)                                                AS name_comment_1,
    TRIM(cslComment2)                                                AS name_comment_2,
    TRIM(cslMemo)                                                    AS name_memo,
    TRIM(csmDirections)                                              AS name_directions,
    TRIM(csmCrossStreet)                                             AS name_cross_street,
    TRIM(cslCrmID)                                                   AS id_crm,
    cslBuyerAddressID                                                AS id_buyer_address,
    cslPartyLocationID                                               AS id_party_location,
    cslRouteAddressID                                                AS id_route_address,
    cslReturnAddressID                                               AS id_return_address,
    TRIM(cslReturnAddressName)                                       AS name_return_address,
    TRIM(csmMsa_Fips)                                                AS code_msa_fips,
    csmRMCityNumber                                                  AS code_rm_city,
    TRIM(cslTaxExempt)                                               AS code_tax_exempt,
    CAST(cslCustomerSegment AS INT)                                  AS num_customer_segment,
    TRIM(cslDefaultOrderType1)                                       AS code_default_order_type_1,
    TRIM(cslDefaultOrderType2)                                       AS code_default_order_type_2,
    TRIM(cslDefaultOrderType3)                                       AS code_default_order_type_3,
    TRIM(cslDefaultOrderType4)                                       AS code_default_order_type_4,
    CAST(csmShled AS INT)                                            AS num_ship_lead_days,
    TRIM(cslDeliveryUnitOfMeasure)                                   AS code_delivery_uom,
    CAST(cslDeliveryUnitOfMeasureFence AS DECIMAL(10,2))             AS val_delivery_uom_fence,
    TRIM(cslExpressShippingMethod)                                   AS code_express_shipping_method,
    CAST(cslExpressHandlingCharge AS DECIMAL(10,3))                  AS pct_express_handling_charge,
    CAST(cslExpressMinimum AS DECIMAL(10,2))                         AS amt_express_minimum,
    CAST(cslExpressMaximum AS DECIMAL(10,2))                         AS amt_express_maximum,
    TRIM(cslExpressServiceContractNumber)                            AS code_express_service_contract,
    CASE WHEN cslBlockRepOrderEntry = 1 THEN 1 ELSE 0 END           AS is_block_rep_order_entry,
    TRIM(cslAllowFax)                                                AS code_allow_fax,
    TRIM(cslDirectConsumer)                                          AS code_direct_consumer,
    TRIM(cslDirectIncludeShipto)                                     AS code_direct_include_shipto,
    TRIM(cslExportsLCLConsolidationFlag)                             AS code_exports_lcl_consolidation,
    TRIM(cslExportsDocumentCountry)                                  AS code_exports_document_country,
    TRIM(cslExportsProductOnPallets)                                 AS code_exports_product_on_pallets,
    TRIM(cslExportsAppointmentsRequired)                             AS code_exports_appointments_required,
    cslHasDock                                                       AS code_has_dock,
    TRIM(cslUseNegotiatedFreightRate)                                AS code_use_negotiated_freight_rate,
    TRIM(cslUseStandardFreightRate)                                  AS code_use_standard_freight_rate,
    TRIM(cslDoNotRepriceOrders)                                      AS code_do_not_reprice_orders,
    TRIM(cslPricingUseOfflineFiles)                                  AS code_pricing_use_offline_files,
    TRIM(cslDefaultLanguage)                                         AS code_default_language,
    CAST(cslTerritoryEffectivityDate AS DATETIME2(6))                AS dt_territory_effectivity,
    TRIM(cslHasDockUserDate)                                         AS name_has_dock_user_date,
    CAST(cslLastStatusChangeDate AS DATETIME2(6))                    AS dt_last_status_change,
    TRIM(acrec)                                                      AS code_record_status,
    csmAppcd                                                         AS code_app,
    CAST(csmChgAddr AS INT)                                          AS num_change_address,
    CAST(csmChgShip AS INT)                                          AS num_change_ship,
    CAST(csmChgShipExt AS INT)                                       AS num_change_ship_ext,
    CAST(csmChgCust AS INT)                                          AS num_change_customer,
    CAST(commAudit AS INT)                                           AS num_commission_audit,
    CAST(commAudit2 AS INT)                                          AS num_commission_audit_2,
    TRIM(usra)                                                       AS name_created_by,
    CAST(dtea AS DATETIME2(6))                                       AS ts_created,
    TRIM(usrc)                                                       AS name_modified_by,
    CAST(dtec AS DATETIME2(6))                                       AS ts_modified
FROM Enterprise_Lakehouse.Customers.ShippingLocations
WHERE cslCustomerNumber IS NOT NULL