CREATE TABLE [dbo].[CustomerMaster] (

	[Account And ShipTo Number] varchar(8000) NULL, 
	[Account Number] varchar(8000) NULL, 
	[ShipTo Number] varchar(8000) NULL, 
	[Customer Name] varchar(8000) NULL, 
	[Account Name] varchar(8000) NULL, 
	[ShipTo Details] varchar(8000) NULL, 
	[Customer Segment] varchar(8000) NULL, 
	[Business Type Code] varchar(8000) NULL, 
	[Business Type] varchar(8000) NULL, 
	[Reporting Business Type] varchar(8000) NULL, 
	[Customer Group] varchar(8000) NULL, 
	[Address 1] varchar(8000) NULL, 
	[Address 2] varchar(8000) NULL, 
	[Address 3] varchar(8000) NULL, 
	[Address 4] varchar(8000) NULL, 
	[Address 5] varchar(8000) NULL, 
	[City] varchar(8000) NULL, 
	[State] varchar(8000) NULL, 
	[ZipCode] varchar(8000) NULL, 
	[Country] varchar(8000) NULL, 
	[State Code] varchar(8000) NULL, 
	[Country Code] varchar(8000) NULL, 
	[Latitude] decimal(38,6) NULL, 
	[Longitude] decimal(38,6) NULL, 
	[Account Exception Flag] int NULL, 
	[Customer Shipto Name] varchar(8000) NULL, 
	[Shipto AddressID] int NULL, 
	[Primary Sales Territory] varchar(8000) NULL, 
	[Shipto Sales Territory] varchar(8000) NULL, 
	[Customer Account Status] varchar(8000) NULL, 
	[Default Warehouse] varchar(8000) NULL, 
	[Route Zone] varchar(8000) NULL, 
	[Route Region] varchar(8000) NULL, 
	[ABC Account-Current Year] varchar(8000) NULL, 
	[ABC Account-Previous Year] varchar(8000) NULL, 
	[ABC Account-2 Years Ago] varchar(8000) NULL, 
	[Commission Code] varchar(8000) NULL, 
	[Account Group] varchar(8000) NULL
);