CREATE TABLE [dbo].[FiscalCal] (

	[Transaction Date] date NULL, 
	[Integer Date] int NULL, 
	[Mapics Date] int NULL, 
	[Day of Week] varchar(8000) NULL, 
	[Fiscal Week Num] bigint NULL, 
	[FW Desc] varchar(8000) NULL, 
	[Fiscal Year Week Num] int NULL, 
	[Fiscal Month Num] bigint NULL, 
	[FM Desc] varchar(8000) NULL, 
	[Fiscal Month Name] varchar(8000) NULL, 
	[Fiscal Year Month Num] int NULL, 
	[Fiscal Month Year Desc] varchar(8000) NULL, 
	[Fiscal Month Calendar Start] date NULL, 
	[Fiscal Quarter Num] bigint NULL, 
	[FQ Desc] varchar(8000) NULL, 
	[Fiscal Year Half Num] smallint NULL, 
	[Fiscal Half Num] bigint NULL, 
	[FH Desc] varchar(8000) NULL, 
	[Fiscal Year] smallint NULL, 
	[FY Desc] varchar(8000) NULL, 
	[Fiscal Week Start] date NULL, 
	[Fiscal Week End] date NULL, 
	[Fiscal Month Start] date NULL, 
	[Fiscal Month End] date NULL, 
	[Fiscal Year Start] date NULL, 
	[Fiscal Year End] date NULL, 
	[Holiday Indicator] varchar(8000) NULL, 
	[Holiday Name] varchar(8000) NULL, 
	[WeekdayWeekend] varchar(8000) NULL, 
	[Calendar Week Num] bigint NULL, 
	[Calendar Month Num] bigint NULL, 
	[Calendar Quarter Num] bigint NULL, 
	[Calendar Year] smallint NULL, 
	[Fiscal Day Indicator] int NULL, 
	[Fiscal Week Indicator] int NULL, 
	[Fiscal Month Indicator] int NULL, 
	[Fiscal Quarter Indicator] int NULL, 
	[Fiscal Year Indicator] int NULL
);