CREATE TABLE [dbo].[ItemMaster] (

	[Item SKU] varchar(8000) NULL, 
	[Item Description] varchar(8000) NULL, 
	[ItemSKU Description] varchar(8000) NULL, 
	[Colors] varchar(8000) NULL, 
	[Series Number] varchar(8000) NULL, 
	[Series Name] varchar(8000) NULL, 
	[Series Description] varchar(8000) NULL, 
	[Ext Series Number] varchar(8000) NULL, 
	[Ext Series Description] varchar(8000) NULL, 
	[Item Ext Series Number] varchar(8000) NULL, 
	[Series Color] varchar(8000) NULL, 
	[Item Grouping] varchar(8000) NULL, 
	[Item Class Code] varchar(8000) NULL, 
	[Item Class Name] varchar(8000) NULL, 
	[Collective Class Code] varchar(8000) NULL, 
	[Collective Class] varchar(8000) NULL, 
	[Responsible Office] varchar(8000) NULL, 
	[Product Line] varchar(8000) NULL, 
	[AFI Finance Division] varchar(8000) NULL, 
	[AFI Sales Division Code] varchar(8000) NULL, 
	[AFI Sales Division] varchar(8000) NULL, 
	[AFI Sales Category Code] varchar(8000) NULL, 
	[AFI Sales Category] varchar(8000) NULL, 
	[Retail Category Code] varchar(8000) NULL, 
	[Retail Category Description] varchar(8000) NULL, 
	[FOB Price] decimal(38,6) NULL, 
	[Import/Domestic Code] varchar(8000) NULL, 
	[Qty In Box] decimal(38,6) NULL, 
	[UOM] varchar(8000) NULL, 
	[Main Piece Item] varchar(8000) NULL, 
	[Main Piece] varchar(8000) NULL, 
	[Primary Vendor] varchar(8000) NULL, 
	[Primary Vendor Name] varchar(8000) NULL, 
	[Item Style Code] varchar(8000) NULL, 
	[Item Style Group] varchar(8000) NULL, 
	[AFI Item Status] varchar(8000) NULL, 
	[Manufacturing Status] varchar(8000) NULL, 
	[Manufacturing Status Change Date] date NULL, 
	[ItemForecastPlannerID] varchar(8000) NULL, 
	[Cubes] decimal(38,6) NULL, 
	[ContainerVolume] decimal(38,6) NULL, 
	[Unit Price] decimal(38,6) NULL, 
	[Current Status] varchar(8000) NULL, 
	[Future Status] varchar(8000) NULL, 
	[Current SCP Manufacturing Status] varchar(8000) NULL, 
	[ItemImage] varchar(8000) NULL, 
	[Image URL] varchar(8000) NULL, 
	[Sales Class Code] varchar(8000) NULL, 
	[Sales Class Description] varchar(8000) NULL, 
	[Marketing Item Status] varchar(8000) NULL, 
	[Marketing Status Description] varchar(8000) NULL, 
	[Discount Class Code] varchar(8000) NULL, 
	[Discount Class Description] varchar(8000) NULL, 
	[Commission Class Code] varchar(8000) NULL, 
	[Commission Class Description] varchar(8000) NULL, 
	[Freight Class Code] varchar(8000) NULL, 
	[Freight Class Description] varchar(8000) NULL, 
	[Country of Origin] varchar(8000) NULL, 
	[CEX Code] varchar(8000) NULL, 
	[Commodity Item] bit NULL, 
	[Market Introduced At] varchar(8000) NULL, 
	[Market Begin Date] date NULL, 
	[Market End Date] date NULL, 
	[Initial Invoice Period] varchar(8000) NULL, 
	[Initial Invoice Qty] decimal(38,6) NULL, 
	[Merchandising Category] smallint NULL, 
	[Child Style Description] varchar(8000) NULL, 
	[Parent Style Description] varchar(8000) NULL, 
	[Price Point] int NULL, 
	[Item Code] varchar(8000) NULL, 
	[Association Code] varchar(8000) NULL, 
	[Default Group] bit NULL, 
	[Sellable Item Flag] varchar(8000) NULL, 
	[ExpressShipFlag] varchar(8000) NULL, 
	[ConsumerChoiceFlag] varchar(8000) NULL, 
	[F123 Product Flag] bit NULL, 
	[HS Core Product Flag] bit NULL, 
	[HS Proprietary Product Flag] bit NULL, 
	[HS Exclusive Flag] bit NULL, 
	[Berkline Product Flag] bit NULL, 
	[Benchcraft Product Flag] bit NULL, 
	[New Millennium Product Flag] bit NULL, 
	[Bardini Product Flag] bit NULL, 
	[Shanghai Store] bit NULL, 
	[Price Point Rating] varchar(8000) NULL, 
	[General Description Code] decimal(38,6) NULL, 
	[General Description] varchar(8000) NULL, 
	[Hold Buy Code] varchar(8000) NULL, 
	[Showroom] varchar(8000) NULL, 
	[HSExclusiveFlag] bit NULL
);