CREATE TABLE [dbo].[SupplyPlanDetailToday] (

	[Item SKU] varchar(8000) NULL, 
	[Warehouse] varchar(8000) NULL, 
	[Week Ending] date NULL, 
	[Beginning Balance] bigint NULL, 
	[Prod - Firm] bigint NULL, 
	[Prod - Plan] bigint NULL, 
	[PO - Firm] bigint NULL, 
	[PO - Plan] bigint NULL, 
	[TI - In Trans] bigint NULL, 
	[TI - Firm] bigint NULL, 
	[TI - Plan] bigint NULL, 
	[Firm Demands] bigint NULL, 
	[Promo Lift] bigint NULL, 
	[Net Forecast] bigint NULL, 
	[TO - Firm] bigint NULL, 
	[TO - Plan] bigint NULL, 
	[Total Receipts] bigint NULL, 
	[Total Est Shipments] bigint NULL, 
	[Total Prod] bigint NULL, 
	[Total PO] bigint NULL, 
	[Total TI] bigint NULL, 
	[Total Demand] bigint NULL, 
	[Total TO] bigint NULL, 
	[SI] bigint NULL, 
	[SS] bigint NULL, 
	[SI -SS] bigint NULL, 
	[SI Neg] bigint NULL, 
	[Demand Fulfillment] bigint NULL, 
	[Snapshot Date] date NULL
);